# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r jotter-backend/requirements.txt
    - name: Test with pytest
      env:
        DATABASE_HOSTNAME: ${{ env.DATABASE_HOSTNAME }} 
        DATABASE_PORT: ${{ env.DATABASE_PORT }} 
        DATABASE_PASSWORD: ${{ env.DATABASE_PASSWORD }} 
        DATABASE_USERNAME: ${{ env.DATABASE_USERNAME }} 
        DATABASE_NAME: ${{ env.DATABASE_NAME }} 
        SECRET_KEY: ${{ env.SECRET_KEY }} 
        ALGORITHM: ${{ env.ALGORITHM }} 
        ACCESS_TOKEN_EXPIRATION_TIME_MINUTES: ${{ env.ACCESS_TOKEN_EXPIRATION_TIME_MINUTES }} 
        BASE_URL: ${{ env.BASE_URL }} 
      run: |
        make test
